[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.155.1"

[[redirects]]
  from = "/projects/*"
  to = "/admin/"
  status = 200

[[redirects]]
  from = "/"
  to = "/form-success/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/form-success/"
  status = 200
